### ISSUE TITLE
Replace singular() function with Doctrine\Common\Inflector\Inflector::singularize().

### ISSUE THREAD

**Issue by coderabbi** [RoundingWellOS/schematic#1]
Why reinvent the wheel -- more coverage, already built. Interested?

**Comment by shadowhand** [comment]
So long as the requirement is [`doctrine/inflector`](https://packagist.org/packages/doctrine/inflector) I'm cool with it.

**Comment by coderabbi** [comment]
Doh! Literally just forked it. 😀

**Comment by shadowhand** [comment]
@coderabbi sorry, I found a situation where inflection was broken and had to fix it. :D

**Comment by coderabbi** [comment]
No worries. I just thought it was funny. I was in the middle of this when I got the email:

![image](https://user-images.githubusercontent.com/790038/27807875-d25589a8-6011-11e7-861b-6a4aeb90bebc.png)

Almost perfect timing. 😀
