### ISSUE TITLE
Tag new version please

### ISSUE THREAD

**Issue by schroedan** [RoundingWellOS/schematic#13]
The merged PR #12 should be tagged as new version `0.6.0` or so...

We are currently testing this package for our needs. Is there any other package known we could use to create POPOs from schema files?

**Comment by shadowhand** [comment]
There [are a few](https://packagist.org/search/?query=schema%20generator). Feel free to use `dev-master` too.

**Comment by shadowhand** [comment]
Tagged `0.6.0`.
